In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("SOYBEAN PRODUCTION $.csv")
df.head()

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,...,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
0,SURVEY,2023,YEAR,NaN,STATE,ILLINOIS,17,NaN,NaN,NaN,...,NaN,NaN,0,NaN,SOYBEANS,"SOYBEANS - PRODUCTION, MEASURED IN $",TOTAL,NOT SPECIFIED,"8,241,030,000",NaN
1,SURVEY,2022,YEAR,NaN,STATE,ILLINOIS,17,NaN,NaN,NaN,...,NaN,NaN,0,NaN,SOYBEANS,"SOYBEANS - PRODUCTION, MEASURED IN $",TOTAL,NOT SPECIFIED,"9,684,675,000",NaN
2,SURVEY,2021,YEAR,NaN,STATE,ILLINOIS,17,NaN,NaN,NaN,...,NaN,NaN,0,NaN,SOYBEANS,"SOYBEANS - PRODUCTION, MEASURED IN $",TOTAL,NOT SPECIFIED,"9,222,525,000",NaN
3,SURVEY,2020,YEAR,NaN,STATE,ILLINOIS,17,NaN,NaN,NaN,...,NaN,NaN,0,NaN,SOYBEANS,"SOYBEANS - PRODUCTION, MEASURED IN $",TOTAL,NOT SPECIFIED,"6,703,500,000",NaN
4,SURVEY,2019,YEAR,NaN,STATE,ILLINOIS,17,NaN,NaN,NaN,...,NaN,NaN,0,NaN,SOYBEANS,"SOYBEANS - PRODUCTION, MEASURED IN $",TOTAL,NOT SPECIFIED,"4,706,770,000",NaN

In [4]:
df = df[['Year','State','Commodity','Value']]

In [ ]:
df.to_excel("SOYBEAN PRODUCTION $.xlsx")